const ingredients = [
  { value: "peanuts", label: "Peanuts" },
  { value: "shellfish", label: "Shellfish" },
  { value: "eggs", label: "Eggs" },
  { value: "milk", label: "Milk" },
  { value: "soy", label: "Soy" },
  { value: "wheat", label: "Wheat" },
  { value: "tree_nuts", label: "Tree Nuts" },
  { value: "fish", label: "Fish" },
  { value: "sesame", label: "Sesame" },
  { value: "mustard", label: "Mustard" },
  { value: "celery", label: "Celery" },
  { value: "sulphites", label: "Sulphites" },
  { value: "lupin", label: "Lupin" },
  { value: "molluscs", label: "Molluscs" },
  { value: "gluten", label: "Gluten" },
  { value: "corn", label: "Corn" },
  { value: "yeast", label: "Yeast" },
  { value: "legumes", label: "Legumes" },
  { value: "nightshades", label: "Nightshades" },
  { value: "citrus_fruits", label: "Citrus Fruits" },
  { value: "berries", label: "Berries" },
  { value: "chocolate", label: "Chocolate" },
  { value: "garlic", label: "Garlic" },
  { value: "onions", label: "Onions" },
  { value: "spices", label: "Spices" },
  { value: "honey", label: "Honey" },
  { value: "caffeine", label: "Caffeine" },
  { value: "alcohol", label: "Alcohol" },
  { value: "shrimp", label: "Shrimp" },
  // Add more allergens as needed
];

export default ingredients;
